### ISSUE TITLE
Furnace don't return

### ISSUE THREAD

**Issue by Yoshun** [cubex2/morefurnaces#5] opened 2018-06-16 17:31 UTC
The diamond furnace does not return fuel when it is broken.

Versions :
- MoreFurnaces : 1.12.2-1.10.5
- Forge : 1.12.2 - 14.23.4.2705

**Comment by Artanis** [comment] 2018-10-04 04:59
This is almost certainly a duplicate of #4.

**Closed** 2018-10-14 08:58 UTC
